export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const FETCH_STATIONS_REQUEST = 'FETCH_STATIONS_REQUEST';
export const FETCH_STATIONS_FAIL = 'FETCH_STATIONS_FAIL';
export const FETCH_STATIONS_SUCCESS = 'FETCH_STATIONS_SUCCESS';
